name: ecom_app
description: "A new Flutter project."


publish_to: 'none'
version: 1.0.0+1


environment:
  sdk: '>=3.2.6 <4.0.0'

# ---------------- PACKAGES ----------------------- #
dependencies:
  flutter:
    sdk: flutter

# ----------- Utility package ---------------- #
  http: ^1.2.0
  intl: ^0.19.0
  logger: ^2.3.0
  url_launcher: ^6.2.6
  flutter_native_splash: ^2.3.11
  lottie: ^3.1.2
  smooth_page_indicator: ^1.1.0

# ------------- icon ------------------- #
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2
# ---------------- State management ---------- #
  get: ^4.6.6
  get_storage: ^2.1.1
# ------------Product specific ----------------#

# ------------------------ PACKAGES END/ ---------------- #

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0


flutter:

  
  uses-material-design: true

# ------------- LOCAL ASSETS -------------------#
  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/
    - assets/logos/

# ------------- LOCAL FONTS ----------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins/Poppins-BlackItalic.ttf
          weight: 900
          style: italic
