// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHG_pXaEOmLOEx1AwC7P50Uc8vDt7Y57k',
    appId: '1:1007057671082:web:783fc6b04a21a5328ed1d3',
    messagingSenderId: '1007057671082',
    projectId: 'ecommerceapp-a863b',
    authDomain: 'ecommerceapp-a863b.firebaseapp.com',
    storageBucket: 'ecommerceapp-a863b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXLC6d4BOgxl7hksDrHv_Fkk_Jji9-3zw',
    appId: '1:1007057671082:android:1f40902523327a498ed1d3',
    messagingSenderId: '1007057671082',
    projectId: 'ecommerceapp-a863b',
    storageBucket: 'ecommerceapp-a863b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEISbvDQHm_DxKu4OfZ2lAkkcnrq5PsHo',
    appId: '1:1007057671082:ios:dcfd8b6f8ee1679f8ed1d3',
    messagingSenderId: '1007057671082',
    projectId: 'ecommerceapp-a863b',
    storageBucket: 'ecommerceapp-a863b.appspot.com',
    androidClientId: '1007057671082-p7q3llt5nspm2c8d7va7i5oigdlcbe52.apps.googleusercontent.com',
    iosClientId: '1007057671082-3opm7fnsqu1c4gktsd1cbfl1m90vcvjp.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecomApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHG_pXaEOmLOEx1AwC7P50Uc8vDt7Y57k',
    appId: '1:1007057671082:web:d53b22d17cb0306b8ed1d3',
    messagingSenderId: '1007057671082',
    projectId: 'ecommerceapp-a863b',
    authDomain: 'ecommerceapp-a863b.firebaseapp.com',
    storageBucket: 'ecommerceapp-a863b.appspot.com',
  );

}